config/routes.rb
Rails.application.routes.draw do

	devise_for :users, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end  
  get 'simple_pages/about'

  get 'simple_pages/contact'

	get 'simple_pages/index'

	get 'simple_pages/landing_page'
	root 'simple_pages#landing_page'

	post 'simple_pages/thank_you'

	post 'payments/create'

	mount ActionCable.server => '/cable'
	#root 'simple_pages#index'
	resources :orders, only: [:index, :show, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bike Store</title>


<!--  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
-->
<!--
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">-->
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
  <body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
          <%= link_to "Store", '/simple_pages/landing_page', { :class=>"navbar-brand" } %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <!--<li class="active">
        <a href="#">Products <span class="sr-only">(current)</span></a></li>
        -->
        <li>
          <%= link_to "Products", products_path %>
        </li>
        <li>
          <%= link_to "Orders", orders_path %>
        </li>
        <li>
          <%= link_to "About", '/simple_pages/about' %>
        </li>
        <li>
          <%= link_to "Contact", '/simple_pages/contact' %>
        </li>
      </ul>
<ul class="nav pull-right">
  <li>
  <% if user_signed_in? %>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  <% else %>
    <%= link_to('Login', new_user_session_path) %>
  <% end %>
  </li>
</ul>
      <ul class="nav navbar-nav navbar-right">
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <!--<input type="text" class="form-control" placeholder="Search">-->

<%= form_with(url: products_path, method: 'get', local: true) do |form| %>
  <%= form.label :q, 'Search for:' %>
  <%= form.text_field :q, id: 'q', value: params[:q], class: "form-control" %>
  <%= form.submit 'Search' %>
<% end %>
        </div>
<!--        <button type="submit" class="btn btn-default">Submit</button>-->
      </form>
<!--        <li><a href="#">Sign Up</a></li>
        <li><a href="#">Login</a></li>-->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<% if notice %>
<p id="notice" class="alert alert-info" role="alert"><%= notice %></p>
<% end %>
<% if alert %>
<p id="alert" class="alert alert-info" role="alert"><%= alert %></p>
<% end %>

    <%= yield %>

<footer>
  &copy; 2017 Bike Berlin
</footer>

  </body>
</html>